# deploy_k8s.yml
---
- name: Deploy and Rollout Weather ML App to Kubernetes
  hosts: production
  become: yes
  tasks:
    - name: Apply Kubernetes Deployment and Service
      ansible.builtin.shell:
        cmd: |
          minikube kubectl -- apply -f /tmp/k8s-deployment.yml
          minikube kubectl -- rollout status deployment/weather-ml-app-deployment
