- hosts: production
  become: yes

  tasks:
    - name: Apply Kubernetes Deployment and Service (as ubuntu)
      become_user: ubuntu
      shell: |
        export KUBECONFIG=/home/ubuntu/.kube/config
        minikube kubectl -- apply -f /tmp/k8s-deployment.yml
        minikube kubectl -- rollout status deployment/weather-ml-app-deployment
